name: Auto Merge PRs

on:
  workflow_call:
    inputs:
      allowed_users:
        description: '以逗号分隔的允许自动合并的用户名列表'
        required: true
        type: string
    secrets:
      pat_token:
        description: '具有写入权限的 Personal Access Token'
        required: true

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: 检查 PR 作者是否在允许列表中
        id: check-user
        run: |
          IFS=',' read -ra USERS <<< "${{ inputs.allowed_users }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          MATCH=false
          for user in "${USERS[@]}"; do
            if [[ "$user" == "$AUTHOR" ]]; then
              echo "Hello, World2222!"
              MATCH=true
              break
            fi
          done
          echo "match=$MATCH"
          echo "AUTHOR=${AUTHOR}"
          echo "USERS=${USERS[@]}"

      - name: 调试信息
        run: |
          echo "AUTHOR=${{ github.event.pull_request.user.login }}"
          echo "USERS=${{ inputs.allowed_users }}"
          echo "MATCH=${{ steps.check-user.outputs.match }}"
          echo "MATCH=${{ steps.check-user.outputs.match == 'true' }}"
          echo "token=${{ secrets.pat_token }}"

      - name: 启用自动合并
        if: ${{ steps.check-user.outputs.match == 'true' }}
        run: |
          echo "Hello, Worl33333!"
          echo "$github.event.pull_request.number"
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto
        env:
          GH_TOKEN: ${{ secrets.pat_token }}
